# Database Tasks
sys-dev:
  dbtype: "SYBASE"
  host: "dbsybase"
  port: "5000"
  user: "sa"
  password_envar: "SYBASEPASSWORD"
  database_name: "master"
sys-dev1:
  dbtype: "SYBASE"
  host: "dbsybase"
  port: "5000"
  user: "sa"
  password_envar: "SYBASEPASSWORD"
  database_name: "master"
# oracle-dev:
#   dbtype: ORACLE
#   host: dboracle
#   port: 1542
#   user: system
#   password_envar: ORACLEPASSWORD
#   database_name: dev
 
 

 
