# Database Tasks
sys-dev1:
  dbtype: "SYBASE"
  host: "dbsybase"
  port: "5000"
  user: "sa"
  password_envar: "SYBASEPASSWORD"
  database_name: "master"
sys-dev2:
  dbtype: "SYBASE"
  host: "dbsybase"
  port: "5000"
  user: "sa"
  password_envar: "SYBASEPASSWORD"
  database_name: "master"
# oracle-dev:
#   dbtype: ORACLE
#   host: dboracle
#   port: 1542
#   user: system
#   password_envar: ORACLEPASSWORD
#   database_name: dev
tasks: 
  -  DumpTableToExcel:
      oracle-dev:
        sql: select * from TABLE
      sys-dev:
        sql: select * from tablex
  - DumpAllTablesToCSV:
      oracle-dev:
      sys-dev:
 
 

