#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  docker-in-docker:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.gitkey:/root/.gitkey
      - /var/run/docker.sock:/var/run/docker.sock 
    command: sleep infinity 
    environment:
      DOCKERIZED: dbpg
      PGUSER: root
      PGPASSWORD: docker 
      PGHOST: dbpg
      PGPORT: 5432
      SYBASE_PASSWORD: myPassword
      ORACLE_SID: dev
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: Docker12345
      ORACLE_CHARACTERSET: 'UTF8'
      JAREXPORT: '/workspace/target/DbTest-jar-with-dependencies.jar'
      GITHUBRELEASE: '/workspace/.devcontainer/release-manager/pyGithubManager.py'
      GITHUBKEY: '/root/.gitkey'
      REPO: 'hung135/dbdifftest'
      SYBASEPASSWORD: myPassword

  # dbpg:
  #   image: postgres
  #   restart: unless-stopped
  #   ports: 
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: docker 

  # dbsybase:
  #   image: nguoianphu/docker-sybase 
  #   restart: unless-stopped
  #   ports:
  #     - 5000:5000
  #   environment:
  #     #Admin user
  #     SYBASE_USER: sa
  #     SYBASE_PASSWORD: myPassword
  dboracle:
    image: oracle/database:12.2.0.1-ee
    restart: unless-stopped
    # ports:
    #   - 1521:1521
    #   - 5500:5500 
    environment:
      ORACLE_SID: dev
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: Docker12345
      ORACLE_CHARACTERSET: 'UTF8'